config/routes.rb
Tpg::Application.routes.draw do
  resources :weeks

  resources :seasons

  resources :teams do
    member do
      get 'join'
      post 'register'
    end
  end

  resources :divisions
  resources :leagues
  resources :games
  devise_for :users

end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :season
  attr_accessible :name
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  load_and_authorize_resource

  # GET /weeks
  # GET /weeks.json
  def index
    @weeks = Week.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weeks }
    end
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
    @week = Week.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @week }
    end
  end

  # GET /weeks/new
  # GET /weeks/new.json
  def new
    @week = Week.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @week }
    end
  end

  # GET /weeks/1/edit
  def edit
    @week = Week.find(params[:id])
  end

  # POST /weeks
  # POST /weeks.json
  def create
    @week = Week.new(params[:week])

    respond_to do |format|
      if @week.save
        format.html { redirect_to @week, notice: 'Week was successfully created.' }
        format.json { render json: @week, status: :created, location: @week }
      else
        format.html { render action: "new" }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weeks/1
  # PUT /weeks/1.json
  def update
    @week = Week.find(params[:id])

    respond_to do |format|
      if @week.update_attributes(params[:week])
        format.html { redirect_to @week, notice: 'Week was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @week.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weeks/1
  # DELETE /weeks/1.json
  def destroy
    @week = Week.find(params[:id])
    @week.destroy

    respond_to do |format|
      format.html { redirect_to weeks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/_form.html.haml
= form_for @week, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :season_id, :class => 'control-label'
    .controls
      = f.number_field :season_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), weeks_path, :class => 'btn'

app/views/weeks/edit.html.haml
- model_class = Week
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/weeks/index.html.haml
- model_class = Week
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:season_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @weeks.each do |week|
      %tr
        %td= link_to week.id, week_path(week)
        %td= week.name
        %td= week.season_id
        %td=l week.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_week_path(week), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), week_path(week), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_week_path, :class => 'btn btn-primary'

app/views/weeks/new.html.haml
- model_class = Week
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/weeks/show.html.haml
- model_class = Week
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @week.name
%p
  %strong= model_class.human_attribute_name(:season_id) + ':'
  %br
  = @week.season_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), weeks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_week_path(@week), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), week_path(@week), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'