config/routes.rb
Tpg::Application.routes.draw do
  resources :weeks

  resources :seasons

  resources :teams do
    member do
      get 'join'
      post 'register'
    end
  end

  resources :divisions
  resources :leagues
  resources :games
  devise_for :users

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :league
  attr_accessible :active, :name
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  load_and_authorize_resource

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  def new
    @season = Season.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(params[:season])
    @season.league = League.find(params[:league_id])

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seasons/1
  # PUT /seasons/1.json
  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.haml
= form_for @season, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :active, :class => 'control-label'
    .controls
      = f.check_box :active, :class => 'check_box'
  .control-group
    = f.label :league_id, :class => 'control-label'
    .controls
      - if @season.id
        %span.input-xlarge.uneditable-input= @season.league.name
      - else
        = select_tag :league_id, option_groups_from_collection_for_select(Game.active_games, :leagues, :name, :id, :name, @season.league_id)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), seasons_path, :class => 'btn'

app/views/seasons/edit.html.haml
- model_class = Season
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/seasons/index.html.haml
- model_class = Season
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:active)
      %th= model_class.human_attribute_name(:league_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @seasons.each do |season|
      %tr
        %td= link_to season.id, season_path(season)
        %td= season.name
        %td= season.active
        %td= season.league_id
        %td=l season.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_season_path(season), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), season_path(season), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_season_path, :class => 'btn btn-primary'

app/views/seasons/new.html.haml
- model_class = Season
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/seasons/show.html.haml
- model_class = Season
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @season.name
%p
  %strong= model_class.human_attribute_name(:active) + ':'
  %br
  = @season.active
%p
  %strong= model_class.human_attribute_name(:league_id) + ':'
  %br
  = @season.league_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), seasons_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_season_path(@season), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), season_path(@season), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'