config/routes.rb
Tpg::Application.routes.draw do
  resources :weeks

  resources :seasons

  resources :teams do
    member do
      get 'join'
      post 'register'
    end
  end

  resources :divisions
  resources :leagues
  resources :games
  devise_for :users

end

app/models/league.rb
class League < ActiveRecord::Base
  resourcify
  belongs_to :game
  has_many :divisions
  has_many :seasons
  attr_accessible :active, :description, :name
  validates_presence_of :description, :name
  validates :active, :inclusion => { :in => [true, false] }

  #
  # Add a user as league admin
  def add_admin(user)
    user.add_role :league_admin, self
  end

  #
  # Remove a user's admin privileges
  def remove_admin(user)
    user.remove_role :league_admin, self
  end

  #
  # Activate the league
  def activate!
    self.active = true
    save
  end

  #
  # Deactivate the league
  def deactivate!
    self.active = false
    save
  end

  #
  # Fetch all admins
  #
  # @return Array
  def admins
    User.with_role(:league_admin, self)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  load_and_authorize_resource

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.where(:active => true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.json
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(params[:league])
    @league.game = Game.find(params[:game_id])

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.json
  def update
    @league = League.find(params[:id])

    params[:admins] ||= []
    current_admins = @league.admins.map { |admin| admin.id.to_s } || []
    new_admins = params[:admins] - current_admins
    deleted_admins = current_admins - params[:admins]

    new_admins.each { |new_admin_id| @league.add_admin User.find(new_admin_id) }
    deleted_admins.each { |deleted_admin_id| @league.remove_admin User.find(deleted_admin_id) }

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.haml
= form_for @league, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field input-xlarge'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area input-xlarge', :rows => 5 
  .control-group
    = f.label :active, :class => 'control-label'
    .controls
      - if !@league.id || @league.game.active?
        = f.check_box :active, :class => 'check_box'
      - else
        = f.check_box :active, :class => 'check_box', :disabled => true
        .help-block
          %p
            %span.label.label-important Cannot activate
            This league cannot be activated because its game is currently inactive.

  .control-group
    = f.label :game_id, :class => 'control-label'
    .controls
      - if @league.id
        %span.input-xlarge.uneditable-input= @league.game.name
      - else
        = select_tag :game_id, options_from_collection_for_select(Game.active_games, :id, :name, @league.game_id)
  .control-group
    %label.control-label Admins
    .controls
      = select_tag :admins, options_from_collection_for_select(User.all, :id, :alias, @league.admins.pluck(:id)), { :multiple => true, :class => 'input-xlarge', :"data-placeholder" => "Enter user aliases ..." }
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), leagues_path, :class => 'btn'

app/views/leagues/edit.html.haml
- model_class = League
.page-header
  %h1
    = @league.game.name
    %small= @league.name
= render :partial => "form"

app/views/leagues/index.html.haml
- model_class = League
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:active)
      %th= model_class.human_attribute_name(:game_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @leagues.each do |league|
      %tr
        %td= link_to league.id, league_path(league)
        %td= league.name
        %td= league.description
        %td= league.active
        %td= league.game_id
        %td=l league.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_league_path(league), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), league_path(league), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_league_path, :class => 'btn btn-primary'

app/views/leagues/new.html.haml
- model_class = League
.page-header
  %h1 New League
= render :partial => "form"

app/views/leagues/show.html.haml
- model_class = League
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @league.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @league.description
%p
  %strong= model_class.human_attribute_name(:active) + ':'
  %br
  = @league.active
%p
  %strong= model_class.human_attribute_name(:game_id) + ':'
  %br
  = @league.game_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), leagues_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_league_path(@league), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), league_path(@league), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'