config/routes.rb
Tpg::Application.routes.draw do
  resources :weeks

  resources :seasons

  resources :teams do
    member do
      get 'join'
      post 'register'
    end
  end

  resources :divisions
  resources :leagues
  resources :games
  devise_for :users

end

app/models/division.rb
class Division < ActiveRecord::Base
  resourcify
  belongs_to :league
  attr_accessible :name
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  load_and_authorize_resource

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])
    @division.league = League.find(params[:league_id])

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.haml
= form_for @division, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :league_id, :class => 'control-label'
    .controls
      - if @division.id
        %span.input-xlarge.uneditable-input= @division.league.name
      - else
        = select_tag :league_id, option_groups_from_collection_for_select(Game.active_games, :leagues, :name, :id, :name, @division.league_id)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), divisions_path, :class => 'btn'

app/views/divisions/edit.html.haml
- model_class = Division
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/divisions/index.html.haml
- model_class = Division
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:league_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @divisions.each do |division|
      %tr
        %td= link_to division.id, division_path(division)
        %td= division.name
        %td= division.league_id
        %td=l division.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_division_path(division), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), division_path(division), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_division_path, :class => 'btn btn-primary'

app/views/divisions/new.html.haml
- model_class = Division
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/divisions/show.html.haml
- model_class = Division
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @division.name
%p
  %strong= model_class.human_attribute_name(:league_id) + ':'
  %br
  = @division.league_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), divisions_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_division_path(@division), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), division_path(@division), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'